import 'package:flutter/material.dart';
class FaceBookScreen extends StatefulWidget {
  const FaceBookScreen({super.key});

  @override
  State<FaceBookScreen> createState() => _FaceBookScreenState();
}

class _FaceBookScreenState extends State<FaceBookScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor:Colors.white,
      appBar:
      AppBar(
        backgroundColor: Colors.white,
        actions:[
          SizedBox(width:500),
          Icon(Icons.add,color:Colors.black,),
          SizedBox(width:50),
          Icon(Icons.more_vert,color:Colors.black,),
          SizedBox(width:20),
        ],
        title:Text(
          'FaceBook',style:TextStyle(
          color:Colors.black,
          fontWeight:FontWeight.bold,fontSize:30,
        ),
        ),
        centerTitle:false,
      ),
      body:SingleChildScrollView(
        child:Column(
          children: [
            Row
              (
              children:
              [
                Row
                  (
                  children: [
                    CircleAvatar(
                      radius:40,
                      backgroundImage:AssetImage(
                        'assets/awesome.jpg',
                      ),
                      child:Column(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Icon(Icons.add_circle,color:Colors.green),
                        ],
                      ),
                    ),
                    SizedBox(width:15),
                    Column(
                      children:[
                        Row(
                          children:[
                            Text(
                              'My Status',style:TextStyle(
                              color:Colors.black,fontWeight:FontWeight.bold,
                              fontSize:20,
                            ),
                            ),
                          ],
                        ),

                        SizedBox(height:5),
                        Row
                          (
                          children:[
                            SizedBox(width:30),
                            Text(
                                'click to add status update',
                                style:TextStyle(
                                  color:Colors.blueGrey,
                                  fontSize:10,
                                )
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),

              ],
            ),

            Divider(thickness:5,color:Colors.grey,),
            Row(
              children:[
                SizedBox(width:50),
                Text(
                  'RECENT',style:TextStyle(
                  color:Colors.green,fontSize:30,fontWeight:FontWeight.bold,
                ),
                )
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/beutifull.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Shazii',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 4:34',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/girl2.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Farzana Atif',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 5:03',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/girl5.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Sabuu',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 5:47',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/hijab.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'faria',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 7:34',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/girl8.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Sana',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 7:38',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/hq720.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Rukhsar',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 7:44',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/beutifull.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Shazii',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 4:34',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/girl.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Farisa',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 8:34',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Divider(thickness:0.5,color:Colors.grey,),
            Row(
              children:[
                Row(
                  children:[
                    CircleAvatar(
                      radius:20,
                      backgroundImage:AssetImage('assets/boy2.jpg'),
                    ),
                  ],
                ),
                Column(
                  children:[
                    Row(
                      children:[
                        SizedBox(width:10),
                        Text(
                          'Maniii',style:TextStyle(
                          color:Colors.black,fontWeight:FontWeight.bold,
                          fontSize:20,
                        ),
                        ),
                      ],
                    ),
                    SizedBox(height:5),
                    Row(
                      children:[
                        SizedBox(width:40),
                        Text(
                          'today at 9:34',style:TextStyle(
                          color:Colors.grey,fontSize:20,
                        ),
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),

      ),
    );
  }
}